import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import AOS from 'aos';
import SEO from '../../common/SEO';
import Breadcrumbs from '../../common/Breadcrumbs';
import AuthorReviewer from '../../common/AuthorReviewer';

const TaxNotice143_1Page = () => {
    useEffect(() => {
        AOS.refresh();
        window.scrollTo(0, 0);
    }, []);

    return (
        <main className="font-inter text-white bg-dark-bg pt-24 md:pt-28 overflow-x-hidden">
            <SEO
                title="Income Tax Intimation Section 143(1) Guide | Tax Demand & Refund"
                description="Understand Income Tax Intimation under Section 143(1). What to do if you get a tax demand order, TDS mismatch, arithmetic adjustments or refund delayed."
                canonical="https://acharyaprofessionalaccountants.in/resources/tax-notices/notice-143-1"
            />
            <div className="container mx-auto px-5 md:px-12 lg:px-20 pt-4">
                <Breadcrumbs />
            </div>

            <section className="container mx-auto px-5 md:px-12 lg:px-20 py-12 md:py-16" data-aos="fade-up">
                <div className="max-w-4xl">
                    <span className="text-primary-accent uppercase tracking-[0.2em] text-xs font-semibold">
                        Resources / Tax Notice Guides / Section 143(1)
                    </span>
                    <h1 className="font-montserrat text-3xl md:text-5xl font-bold mt-3 mb-6">
                        Income Tax Intimation <span className="text-primary-accent">Section 143(1) Explained</span>
                    </h1>
                    <p className="text-boulder text-lg leading-relaxed mb-8">
                        An intimation under Section 143(1) of the Income Tax Act is automatically generated by the Centralized Processing Centre (CPC) after your tax return is processed. It compares the income, deductions, and TDS declared in your ITR against the records in 26AS, AIS, and TIS.
                    </p>

                    <AuthorReviewer
                        author="Acharya Tax Notice Resolution Division"
                        reviewer="Chartered Accountant (ICAI)"
                        lastUpdated="September 2026"
                    />

                    <div className="space-y-6 mt-8 text-boulder text-sm md:text-base leading-relaxed">
                        <div className="bg-secondary-dark border border-white/5 rounded-2xl p-6">
                            <h2 className="text-xl font-bold text-white mb-3">3 Types of Section 143(1) Intimations</h2>
                            <ul className="space-y-3">
                                <li>• **No Demand / No Refund:** Your tax calculations match CPC calculations perfectly.</li>
                                <li>• **Tax Refund Determined:** CPC calculated a tax refund higher or equal to your claim.</li>
                                <li>• **Tax Demand Raised:** CPC found an arithmetic error, disallowed a deduction (e.g. 80C mismatch), or detected a TDS shortfall, raising a tax demand notice.</li>
                            </ul>
                        </div>

                        <div className="bg-secondary-dark border border-white/5 rounded-2xl p-6">
                            <h2 className="text-xl font-bold text-white mb-3">Next Steps if You Receive a Demand Order</h2>
                            <ol className="list-decimal pl-5 space-y-2">
                                <li>Compare your filed ITR copy against the CPC computation table in the PDF.</li>
                                <li>If CPC disallowance is incorrect, file a **Rectification Request under Section 154** on the e-filing portal.</li>
                                <li>Do not ignore a tax demand notice, as unpaid demand accrues interest under Section 220(2) at 1% per month.</li>
                            </ol>
                        </div>
                    </div>

                    <div className="bg-gradient-to-r from-secondary-dark to-dark-bg border border-primary-accent/20 rounded-2xl p-8 text-center mt-10">
                        <h3 className="text-2xl font-bold text-white mb-3">Need Help Resolving a Section 143(1) Tax Demand?</h3>
                        <p className="text-boulder text-sm mb-6 max-w-xl mx-auto">
                            Send your intimation order to Acharya. Our chartered accountants analyze CPC mismatches and file online rectifications or Section 154 responses.
                        </p>
                        <Link to="/contact" className="inline-block bg-primary-accent text-dark-bg font-bold px-8 py-3 rounded-full hover:bg-white transition-colors">
                            Submit Notice for Professional Review
                        </Link>
                    </div>
                </div>
            </section>
        </main>
    );
};

export default TaxNotice143_1Page;
