import React from 'react';
import {
    FaBuilding,
    FaUserTie,
    FaHandshake,
    FaCity,
    FaHeart,
    FaPiggyBank,
    FaTractor,
    FaCalendarCheck,
    FaFileInvoice,
    FaFileContract,
    FaIdBadge,
    FaBookOpen,
    FaUsers,
    FaIdCard,
    FaUserPlus,
    FaFileSignature,
    FaClipboardList,
    FaExchangeAlt,
    FaMapMarkerAlt,
    FaTag,
    FaCoins,
    FaBullseye,
    FaUserFriends,
    FaTrashRestore,
    FaLevelUpAlt,
    FaBed,
    FaBriefcase,
    FaClipboardCheck,
    FaEnvelopeOpenText,
    FaGavel,
    FaBalanceScale,
    FaSearchDollar,
    FaRocket,
    FaUserMd,
    FaRandom,
    FaPowerOff,
    FaWarehouse,
    FaEdit,
    FaBan,
    FaCalendarAlt,
    FaMinusCircle,
    FaBook,
    FaCheckCircle,
    FaCheckDouble,
    FaFileExport,
    FaFileImport,
    FaUsersSlash,
    FaListOl,
    FaRetweet,
    FaQrcode,
    FaIndustry,
    FaShoppingCart,
    FaPlane,
    FaHardHat,
    FaLaptopCode,
    FaHandHoldingUsd,
    FaMoneyBillWave,
    FaGlobe,
    FaChartLine,
    FaSearch,
    FaCalculator,
    FaBoxes,
    FaFolderOpen,
    FaArrowLeft,
    FaArrowRight,
    FaWhatsapp,
    FaCheck,
    FaStar,
    FaUser,
    FaStore,
    FaClock,
    FaCogs,
    FaExpandArrowsAlt,
    FaTimesCircle,
    FaLaptopHouse,
    FaCertificate,
    FaFileAlt,
    FaUserGraduate,
    FaPhoneAlt,
    FaChalkboardTeacher,
    FaInfoCircle,
    FaLinkedinIn,
    FaTwitter,
    FaFacebookF,
    FaInstagram,
    FaAward,
    FaFileInvoiceDollar,
    FaEye,
    FaLightbulb,
    FaGraduationCap,
    FaLayerGroup,
    FaChevronUp,
    FaChevronDown,
    FaPaperPlane,
    FaEnvelope,
    FaCalendar,
    FaComment,
    FaPercent,
    FaLock,
    FaFileExcel,
    FaChartPie
} from 'react-icons/fa';

const iconMap = {
    'fa-circle-check': FaCheckCircle,
    'fa-percent': FaPercent,
    'fa-lock': FaLock,
    'fa-file-excel': FaFileExcel,
    'fa-chart-pie': FaChartPie,
    'fa-magnifying-glass-chart': FaSearchDollar,
    'fa-building': FaBuilding,
    'fa-user-tie': FaUserTie,
    'fa-handshake': FaHandshake,
    'fa-city': FaCity,
    'fa-heart': FaHeart,
    'fa-piggy-bank': FaPiggyBank,
    'fa-tractor': FaTractor,
    'fa-calendar-check': FaCalendarCheck,
    'fa-file-invoice': FaFileInvoice,
    'fa-file-contract': FaFileContract,
    'fa-id-badge': FaIdBadge,
    'fa-book-open': FaBookOpen,
    'fa-users': FaUsers,
    'fa-id-card': FaIdCard,
    'fa-user-plus': FaUserPlus,
    'fa-file-signature': FaFileSignature,
    'fa-clipboard-list': FaClipboardList,
    'fa-exchange-alt': FaExchangeAlt,
    'fa-map-marker-alt': FaMapMarkerAlt,
    'fa-tag': FaTag,
    'fa-coins': FaCoins,
    'fa-bullseye': FaBullseye,
    'fa-user-friends': FaUserFriends,
    'fa-trash-restore': FaTrashRestore,
    'fa-level-up-alt': FaLevelUpAlt,
    'fa-bed': FaBed,
    'fa-briefcase': FaBriefcase,
    'fa-clipboard-check': FaClipboardCheck,
    'fa-envelope-open-text': FaEnvelopeOpenText,
    'fa-gavel': FaGavel,
    'fa-balance-scale': FaBalanceScale,
    'fa-search-dollar': FaSearchDollar,
    'fa-rocket': FaRocket,
    'fa-user-md': FaUserMd,
    'fa-random': FaRandom,
    'fa-power-off': FaPowerOff,
    'fa-warehouse': FaWarehouse,
    'fa-edit': FaEdit,
    'fa-ban': FaBan,
    'fa-calendar-alt': FaCalendarAlt,
    'fa-minus-circle': FaMinusCircle,
    'fa-book': FaBook,
    'fa-check-circle': FaCheckCircle,
    'fa-check-double': FaCheckDouble,
    'fa-file-export': FaFileExport,
    'fa-file-import': FaFileImport,
    'fa-users-slash': FaUsersSlash,
    'fa-list-ol': FaListOl,
    'fa-retweet': FaRetweet,
    'fa-qrcode': FaQrcode,
    'fa-industry': FaIndustry,
    'fa-shopping-cart': FaShoppingCart,
    'fa-plane': FaPlane,
    'fa-hard-hat': FaHardHat,
    'fa-laptop-code': FaLaptopCode,
    'fa-hand-holding-usd': FaHandHoldingUsd,
    'fa-money-bill-wave': FaMoneyBillWave,
    'fa-globe': FaGlobe,
    'fa-chart-line': FaChartLine,
    'fa-search': FaSearch,
    'fa-calculator': FaCalculator,
    'fa-boxes': FaBoxes,
    'fa-folder-open': FaFolderOpen,
    'fa-arrow-left': FaArrowLeft,
    'fa-arrow-right': FaArrowRight,
    'fa-whatsapp': FaWhatsapp,
    'fa-check': FaCheck,
    'fa-star': FaStar,
    'fa-user': FaUser,
    'fa-store': FaStore,
    'fa-clock': FaClock,
    'fa-cogs': FaCogs,
    'fa-expand-arrows-alt': FaExpandArrowsAlt,
    'fa-times-circle': FaTimesCircle,
    'fa-laptop-house': FaLaptopHouse,
    'fa-certificate': FaCertificate,
    'fa-file-alt': FaFileAlt,
    'fa-user-graduate': FaUserGraduate,
    'fa-phone-alt': FaPhoneAlt,
    'fa-chalkboard-teacher': FaChalkboardTeacher,
    'fa-circle-info': FaInfoCircle,
    'fa-linkedin-in': FaLinkedinIn,
    'fa-twitter': FaTwitter,
    'fa-facebook-f': FaFacebookF,
    'fa-instagram': FaInstagram,
    'fa-award': FaAward,
    'fa-file-invoice-dollar': FaFileInvoiceDollar,
    'fa-eye': FaEye,
    'fa-lightbulb': FaLightbulb,
    'fa-graduation-cap': FaGraduationCap,
    'fa-layer-group': FaLayerGroup,
    'fa-chevron-up': FaChevronUp,
    'fa-chevron-down': FaChevronDown,
    'fa-paper-plane': FaPaperPlane,
    'fa-envelope': FaEnvelope,
    'fa-calendar': FaCalendar,
    'fa-comment': FaComment
};

const DynamicFaIcon = ({ name, className }) => {
    if (!name) return null;
    // Handle case where name might include 'fa-' prefix or not, though our map uses it
    const IconComponent = iconMap[name];

    if (!IconComponent) {
        console.warn(`Icon not found: ${name}`);
        return null;
    }

    return <IconComponent className={className} />;
};

export default DynamicFaIcon;
